// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8F1SYxB8T-Jg9pBIg6BgAyB4Uo0jXKDE',
    appId: '1:898243552348:android:a87654b64714520ed77299',
    messagingSenderId: '898243552348',
    projectId: 'you-chat-155b8',
    storageBucket: 'you-chat-155b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKyQvI23hGWV4c9V0qN5EFH6GPik_dlM',
    appId: '1:898243552348:ios:910ee410589fa741d77299',
    messagingSenderId: '898243552348',
    projectId: 'you-chat-155b8',
    storageBucket: 'you-chat-155b8.appspot.com',
    androidClientId: '898243552348-4mu8kcr8r4158o5barj6ln9qrjtfa1jf.apps.googleusercontent.com',
    iosClientId: '898243552348-qb2kg9h0s2t531iqq92tnotqo19c3dpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.youChat',
  );
}
